waikiki/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<int:pk>/update/', views.update, name='update'),
]

waikiki/ono/urls.py
from django.urls import path

from . import views

app_name = 'ono'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:user_id>/dashboard/', views.dashboard, name="dashboard"),
    path('<int:user_id>/collection/', views.collection, name="collection"),
    path('<int:user_id>/mint/', views.mint, name="mint"),
    path('search/', views.search, name='search'),
    path('test/image/', views.test_image, name="test_image"),
    path('test/minting/', views.test_minting, name="test_minting"),
    path('test/makecontract/', views.make_contract, name="make_contract"),
    path('test/maketoken/', views.make_token, name="make_token")

]

waikiki/waikiki/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('ono.urls')),
    path('common/', include('common.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waikiki/ono/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import ArrayField

# Create your models here.
# https://www.webforefront.com/django/modeldatatypesandvalidation.html

# parent : default user
### id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, data_joined
# Ref. https://chagokx2.tistory.com/60


class OnoUser(AbstractUser):
    eth_address = models.CharField(max_length=255)
    collection_ids = ArrayField(models.IntegerField(
        null=True, blank=True), null=True, blank=True)
    symbol = models.ImageField(upload_to='user/symbol/', blank=True, null=True,
                               default='white-image.png')  # default='album_logos/no-image.jpg')


class Collection(models.Model):
    id = models.BigAutoField(primary_key=True)
    user_id = models.ForeignKey(OnoUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    symbol = models.ImageField(
        upload_to='collection/symbol/', blank=True, null=True, default='white-image.png')
    blockchain = models.PositiveIntegerField()
    token_size = models.PositiveIntegerField()
    media_type = models.PositiveIntegerField()
    contract_address = models.TextField(blank=True)
    description = models.TextField(blank=True)
    owner_address = models.TextField(blank=True, null=True)
    created_date = models.DateTimeField('date created', auto_now_add=True)
    updated_date = models.DateTimeField('date updated', auto_now=True)

    def __str__(self):
        return "[collection] id: " + str(self.id) + ", title: " + self.title


class Abi(models.Model):
    id = models.OneToOneField(Collection, primary_key=True, on_delete=models.CASCADE)
    abi = models.TextField(blank=True)

    def __str__(self):
        return "[collection] id: " + str(self.id)

class Token(models.Model):
    id = models.BigAutoField(primary_key=True)
    collection_id = models.ForeignKey(Collection, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    media_type = models.PositiveIntegerField()
    ipfs_path = models.TextField(blank=True)
    token_path = models.TextField(blank=True)
    sha256_hash = models.TextField(blank=True)
    description = models.TextField(blank=True)
    owner = models.CharField(max_length=255, blank=True)
    owner_id = models.BigIntegerField(null=True)
    owner_address = models.TextField(blank=True)
    created_date = models.DateTimeField('date created', auto_now_add=True)
    updated_date = models.DateTimeField('date updated', auto_now=True)
    token_image = models.ImageField(
        upload_to='collection/tokens/', blank=True, null=True, default='white-image.png')

    def __str__(self):
        return "[token] id: " + str(self.id) + ", image: " + str(self.ipfs_path)


class TempImage(models.Model):
    id = models.BigAutoField(primary_key=True)
    image = models.ImageField(upload_to='temp/', blank=True, null=True)

    def __str__(self):
        return "[temp image] id: " + str(self.id) + ", image: " + str(self.image)


class Crawled(models.Model):
    id = models.BigAutoField(primary_key=True)
    blockchain = models.PositiveIntegerField()
    collection_id = models.CharField(max_length=255)
    collection_title = models.CharField(max_length=255)
    token_id = models.CharField(max_length=255)
    token_title = models.CharField(max_length=255)
    media_type = models.PositiveIntegerField()
    ipfs_path = models.TextField(blank=True)
    token_path = models.TextField(blank=True)
    sha256_hash = models.TextField(blank=True)
    description = models.TextField(blank=True)
    created_date = models.DateTimeField('date created', auto_now_add=True)
    updated_date = models.DateTimeField('date updated', auto_now=True)
    blockchain = models.PositiveIntegerField()
    owner_address = models.TextField(blank=True)


class TempUrl(models.Model):
    id = models.BigAutoField(primary_key=True)
    ipfs_path = models.TextField(blank=True)

# class TestInfo(models.Model):
#     user_id = models.CharField(max_length=20)
#     user_name = models.CharField(max_length=100)
#     file_path = models.CharField(max_length=255)
#     ipfs_path = models.CharField(max_length=255)
#     created_date = models.DateTimeField('date created', auto_now_add=True)
#     updated_date = models.DateTimeField('date updated', auto_now=True)
#     etc = models.CharField(max_length=255, null=True)
#     image = models.ImageField(upload_to='images/', blank=True, null=True)

#     def __str__(self):
#         return "user_id: " + self.user_id + ", image: " + str(self.image)

waikiki/ono/views.py
import json
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponse
from django.http import JsonResponse
from django.http import Http404
from ono.models import Collection, OnoUser, Token, TempImage, Abi
from django.contrib.auth import get_user_model
from ono.modules.ono_engine.imge_comparison import compare_image
from ono.modules.ono_web3.nft_contract import search_tx, create_nft_contract, mint_item
from ono.modules.ono_utils.ono_utils import removeFile
import os
import ipfsApi


def index(request):
    collections = Collection.objects.all()
    tokens = Token.objects.all()

    return render(request, 'ono/index.html', {'collections': collections, 'tokens': tokens})


def dashboard(request, user_id):
    onoUser = get_object_or_404(OnoUser, pk=user_id)
    print("[dashboard] onoUser = ", onoUser)

    # Organisation.objects.filter(name__iexact = 'Fjuk inc')
    collections = Collection.objects.filter(user_id=onoUser)
    if len(collections) != 0:
        tokens = Token.objects.filter(collection_id=collections[0])
        return render(request, 'ono/dashboard.html', {'collections': collections, 'tokens': tokens})

    return render(request, 'ono/dashboard.html')


def search(request):
    print("[", request.method, "], /search")

    if request.method == 'POST':
        print("search requested = ", request.POST['search'])

        response = {
            "search_text": request.POST['search'],
            "result": search_tx(request.POST['search'])
        }

    else:
        return redirect('../')

    return render(request, 'ono/search_result.html', response)


def collection(request, user_id):
    print("[", request.method, "], /", user_id, "/collection")

    response = {
        "result": "failed",
        "reason": "<TBD>"
    }
    if request.method == 'POST':
        print('[ Request ] ', request)

        # id, user_id, title, symbol, blockchain, token_size, media_type, contract_address, description, create_date, updated_date
        onoUser = get_object_or_404(OnoUser, pk=user_id)

        collection = Collection()
        collection.user_id = onoUser
        collection.title = request.POST['title']
        for img in request.FILES.getlist('symbol'):
            collection.symbol = img
            break
        collection.blockchain = request.POST['blockchain']
        collection.token_size = request.POST['token_size']
        collection.media_type = request.POST['media_type']
        collection.description = request.POST['description']
        r = create_nft_contract(
            onoUser.eth_address,
            request.POST['private_key'],
            collection.title,
            "symbol"
        )
        collection.contract_address = r['contract_address']
        collection.save()

        abi = Abi()
        abi.id = collection
        abi.abi = json.dumps(r['abi'])
        abi.save()

        response = {
            "result": "successful",
            "reason": "OK"
        }

    else:
        print('..')
        return render(request, 'ono/collection.html')

    return render(request, 'ono/result.html', response)


def mint(request, user_id):
    print("[", request.method, "], /", user_id, "/mint")

    response = {
        "result": "failed",
        "reason": "<TBD>"
    }
    if request.method == 'POST':
        print('[ Request ] ', request)

        # id, collection_id, title, media_type, ipfs_path, token_path, sha256_hash, description, owner, created_date, updated_date
        # collections = get_list_or_404(Collection, user_id=user_id)
        collection = get_object_or_404(
            Collection, pk=int(request.POST['collection_id']))

        token = Token()
        # token.collection_id = collections[int(request.POST['collection_id'])]
        token.collection_id = collection

        onoUser = get_object_or_404(OnoUser, pk=user_id)
        # onoUser = get_object_or_404(OnoUser, pk=token.collection_id.user_id)

        token.title = request.POST['title']
        token.media_type = request.POST['media_type']
        # token.ipfs_path = request.POST['ipfs_path']
        # token.token_path = request.POST['token_path']
        # token.sha256_hash = request.POST['sha256_hash']
        token.description = request.POST['description']
        # token.owner = request.POST['owner']
        token.owner_address = onoUser.eth_address
        for img in request.FILES.getlist('token_image'):
            token.token_image = img
            break

        # 이미지 판단 시작 [
        tempImage = TempImage()
        tempImage.image = token.token_image
        tempImage.save()

        image_response = compare_image(os.path.join(
            os.getcwd() + "/media/" + str(tempImage.image)))
        print("[image_response] ", image_response)

        # 유사도 판단
        if image_response['similarity'] < 99:
            print("[similarity] This is not a scam. Store item into DB.")
            api = ipfsApi.Client('127.0.0.1', 5001)
            res = api.add(os.path.join(
                os.getcwd() + "/media/" + str(tempImage.image)))
            print("[IPFS RES] ", res[0]['Hash'])
            token.ipfs_path = "http://127.0.0.1:8080/ipfs/" + \
                str(res[0]['Hash'])
            token.save()

            abi = get_object_or_404(Abi, pk=token.collection_id)
            r = mint_item(onoUser.eth_address,
                          request.POST['private_key'],
                          token.collection_id.contract_address,
                          abi.abi,
                          onoUser.eth_address,
                          token.id,
                          token.ipfs_path)

            response = {
                "result": "successful",
                "reason": "OK",
                "similarity": image_response['similarity'],
                "duration": image_response['duration'],
                "orig_path": image_response['path'],
                "img_path": str(tempImage.image)
            }
        else:
            print("[similarity] This is a scam!!!")
            response = {
                "result": "failed",
                "reason": "Similarity is so high.",
                "similarity": image_response['similarity'],
                "duration": image_response['duration'],
                "orig_path": image_response['path'],
                "img_path": str(tempImage.image)
            }
        # 이미지 판단 끝 ]

    else:
        print('..')
        # collections = list(Collection.objects.filter(user_id=user_id))
        # get_object_or_404(Collection, user_id=user_id)
        # print("[ collections ] ", collections)
        return render(request, 'ono/mint.html')

    return render(request, 'ono/result.html', response)


def test_image(request):
    print("[", request.method, "], test/image")

    response = {
        "result": "failed",
        "reason": "<TBD>"
    }
    if request.method == 'POST':
        print('[ Request ] ', request)

        tempImage = TempImage()

        for img in request.FILES.getlist('test_image'):
            tempImage.image = img
            break
        tempImage.save()

        # 이미지 판단 시작 [
        image_response = compare_image(os.path.join(
            os.getcwd() + "/media/" + str(tempImage.image)))
        print("[image_response] ", image_response)

        '''
        <TBD>
        response 판단 후, 유사도 판단에 따라 등록 여부를 결정.
        '''
        # 이미지 판단 끝 ]
        removeFile("/media/", str(tempImage.image))
        tempImage.delete()  # delete column from table

        response = {
            "result": "successful",
            "reason": "OK",
            "similarity": image_response['similarity'],
            "duration": image_response['duration']
        }

    else:
        print('..')
        return render(request, 'ono/test_image.html')

    return render(request, 'ono/result.html', response)


def test_minting(request):
    print("[", request.method, "], /test/minting")

    if request.method == 'POST':
        # store DB - tested (20220428)
        # ti = TestInfo() #user_id=user_id_, user_name=user_name_, file_path="", ipfs_path="")
        # ti.user_id = request.POST['user_id']
        # ti.user_name = request.POST['user_name']

        # for img in request.FILES.getlist('images'):
        #     ti.image = img
        #     break;

        # print("user_id = ", ti.user_id, ", image = ", ti.image)

        # ti.save()

        response = {
            "result": "successful",
            "reason": "OK"
        }

        # return HttpResponse(json.dumps(response), content_type = "application/json")
    else:
        response = {
            "result": "failed",
            "reason": "Request method is GET"
        }

        # return HttpResponse(json.dumps(response), content_type = "application/json")

    return render(request, 'ono/result.html', response)
    # raise Http404("Oops!...")
    # return HttpResponse(response)


def make_contract(request):
    print("[", request.method, "], /test/makecontract")

    # if request.method == 'POST':
    response = {
        "search_text": "",
        "result": create_nft_contract()
    }

    # else:
    #     return redirect('../')

    return render(request, 'ono/search_result.html', response)


def make_token(request):
    print("[", request.method, "], /test/maketoken")

    response = {
        "search_text": "",
        "result": mint_item()
    }

    return render(request, 'ono/search_result.html', response)

waikiki/templates/ono/collection.html
{% extends 'ono/base.html' %}
{% load static %}
{% block content %}
<script>
    $(document).ready(function () {
        $.getScript("{% static 'js/ono-0.1.0.js' %}", function () {
        });
    });

    function submit_loading() {
        $("#submit_button").addClass('loading');
    }
</script>

<div class="ui stackable four column centered grid" style="margin:auto;">
    <div class="two column centered row">
        <div class="column" style="padding-top:25px;">
            <form class="ui form" action="{% url 'ono:collection' user.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="field">
                    <label>User ID</label>
                    <input type="text" name="user_id" placeholder="User ID" value="{{ user.id }}" disabled>
                </div>
                <div class="field">
                    <label>User Name</label>
                    <input type="text" name="user_name" placeholder="User Name" value="{{ user.username }}" disabled>
                </div>
                <!-- <div class="field">
                    <label>User Address</label>
                    <input type="text" name="user_address" placeholder="User Address" value="{{ user.eth_address }}" disabled>
                </div> -->
                <div class="field">
                    <label>Private Key</label>
                    <input type="text" name="private_key" placeholder="Private Key">
                </div>
                <div class="field">
                    <label>Title</label>
                    <input type="text" name="title" placeholder="Title">
                </div>
                <div class="field">
                    <label>Symbol</label>
                    <input type="file" name="symbol" id="symbol" accept="image/*" multiple>
                </div>
                <div class="field">
                    <label>Blockchain (1: ETH)</label>
                    <input type="number" name="blockchain" placeholder="Blockchain" value="1">
                </div>
                <div class="field">
                    <label>Token Size</label>
                    <input type="number" name="token_size" placeholder="Token size">
                </div>
                <div class="field">
                    <label>Media Type (1: Image)</label>
                    <input type="number" name="media_type" placeholder="Token size" value="1">
                </div>
                <!-- <div class="field">
                    <label>Contract Address</label>
                    <input type="text" name="contract_address" placeholder="Contract Address">
                </div> -->
                <div class="field">
                    <label>Description</label>
                    <input type="text" name="description" placeholder="Description">
                </div>
                <div align="right">
                    <button class="ui blue submit button" type="submit" id="submit_button"
                        onClick="submit_loading()">Submit</button>
                </div>
            </form>
        </div>

        <div class="ui divider"></div>

    </div>
    <div class="one column centered row">
        <div class="right aligned column">
            <a href="https://github.com/waikiki-korea" target="_blank"><img
                    src="{% static 'img/GitHub-Mark-64px.png' %}" style="width:25px;"></a>
            <p>Copyright &copy; 2022 <b>Team Waikiki</b> all rights reserved.</p>
        </div>
    </div>
</div>
{% endblock %}

waikiki/templates/ono/mint.html
{% extends 'ono/base.html' %}
{% load static %}
{% block content %}
<script>
    $(document).ready(function () {
        $.getScript("{% static 'js/ono-0.1.0.js' %}", function () {
        });
    });

    function submit_loading() {
        $("#mint_submit_button").addClass('loading');
    }
</script>

<div class="ui stackable four column centered grid" style="margin:auto;">
    <div class="two column centered row">
        <div class="column" style="padding-top:25px;">
            <form class="ui form" action="{% url 'ono:mint' user.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="field">
                    <label>User ID</label>
                    <input type="text" name="user_id" placeholder="User ID" value="{{ user.id }}" disabled>
                </div>
                <div class="field">
                    <label>User Name</label>
                    <input type="text" name="user_name" placeholder="User Name" value="{{ user.username }}" disabled>
                </div>
                <div class="field">
                    <label>Private Key</label>
                    <input type="text" name="private_key" placeholder="Private Key">
                </div>
                <div class="field">
                    <label>Blockchain (1: ETH)</label>
                    <input type="number" name="blockchain" placeholder="Blockchain" value="1">
                </div>
                <div class="field">
                    <label>Collection ID</label>
                    <input type="text" name="collection_id" placeholder="Collection ID" value="1">
                </div>
                <div class="field">
                    <label>Title</label>
                    <input type="text" name="title" placeholder="Title">
                </div>
                <div class="field">
                    <label>Media Type (1: Image)</label>
                    <input type="number" name="media_type" placeholder="Token size" value="1">
                </div>
                <!-- <div class="field">
                    <label>IPFS Path</label>
                    <input type="text" name="ipfs_path" placeholder="IPFS Path">
                </div>
                <div class="field">
                    <label>Token Path</label>
                    <input type="text" name="token_path" placeholder="Token Path">
                </div>
                <div class="field">
                    <label>SHA256 Hash</label>
                    <input type="text" name="sha256_hash" placeholder="SHA256 Hash">
                </div> -->
                <div class="field">
                    <label>Description</label>
                    <input type="text" name="description" placeholder="Description">
                </div>
                <!-- <div class="field">
                    <label>Owner</label>
                    <input type="text" name="owner" placeholder="Owner">
                </div> -->
                <div class="field">
                    <label>Token Image</label>
                    <input type="file" name="token_image" id="token_image" accept="image/*" multiple>
                </div>
                <div align="right">
                    <button class="ui blue submit button" type="submit" id="mint_submit_button"
                        onClick="submit_loading()">Submit</button>
                </div>
            </form>
        </div>

        <div class="ui divider"></div>

    </div>
    <div class="one column centered row">
        <div class="right aligned column">
            <a href="https://github.com/waikiki-korea" target="_blank"><img
                    src="{% static 'img/GitHub-Mark-64px.png' %}" style="width:25px;"></a>
            <p>Copyright &copy; 2022 <b>Team Waikiki</b> all rights reserved.</p>
        </div>
    </div>
</div>
{% endblock %}

waikiki/templates/ono/navbar.html
<div class="ui container right aligned" style="padding-top:5px;">

    <form class="ui form" action="{% url 'ono:search' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="ui input" style="margin-right:40px;">
            <input type="text" name="search" id="search" placeholder="Search Tx"
                value="{{ form.search.value|default_if_none:'' }}" style="margin-right:2px;">
            <button class="ui submit blue icon button" type="submit" id="submit_button"><i
                    class="icon search"></i></button>
        </div>
    </form>
</div>

<div class="ui container" style="padding-top:5px;">
    <div class="ui menu" style="height:55px;background-color:#8BD8BD;">
        <a class="header item" href="/" style="color:#243665;background-color:#8BD8BD;">One-n-Only</a>
        {% if user.is_authenticated %}
        <a class="item" href="{% url 'ono:dashboard' user.id %}">
            Dashboard
        </a>
        <a class="item" href="{% url 'ono:collection' user.id %}">
            Collection
        </a>
        <a class="item" href="{% url 'ono:mint' user.id %}">
            Mint
        </a>
        {% else %}
        <a class="item" href="{% url 'common:login' %}">
            Collection
        </a>
        <a class="item" href="{% url 'common:login' %}">
            Mint
        </a>
        {% endif %}
        <!-- TODO: DELETE THESE MENUS -->
        <!-- <a class="item" href="{% url 'ono:make_contract' %}">
            make contract
        </a>
        <a class="item" href="{% url 'ono:make_token' %}">
            make token
        </a>
        <a class="item" href="{% url 'ono:test_image' %}">
            Test image
        </a> -->
        <div class="right menu">
            {% if user.is_authenticated %}
            <a class="item" href="{% url 'common:update' pk=user.id %}">{{ user.username }}</a>
            <a class="item ui red label" href="{% url 'common:logout' %}">Sign out</a>
            {% else %}
            <a class="item" href="{% url 'common:login' %}">Sign in</a>
            <a class="item" href="{% url 'common:signup' %}">Sign up</a>
            {% endif %}
        </div>
    </div>
</div>

waikiki/templates/ono/result.html
{% extends 'ono/base.html' %}
{% load static %}
{% block content %}
<script>
    $(document).ready(function () {
        $.getScript("{% static 'js/ono-0.1.0.js' %}", function () {
            if ("{{ result }}" == 'successful') {
                $('#result_box').addClass("green");
            } else {
                $('#result_box').addClass("red");
            }

        });
    });
</script>

<div class="ui stackable four column centered grid" style="margin:auto;">
    <div class="two column centered row">
        <div class="column" style="padding:50px 0 20px 0;">
            <div class="ui message" id="result_box">
                <div class="header">
                    Your request was {{ result }}.
                </div>
                <p>{{ reason }}</p>
            </div>
            {% if similarity %}

            <div class="ui internally celled grid">
                <div class="row">
                    <div class="three wide column center aligned">
                        Your Image
                    </div>
                    <div class="ten wide column center aligned">
                        Information
                    </div>
                    <div class="three wide column center aligned">
                        Similar Image
                    </div>
                </div>
                <div class="row">
                    <div class="three wide column">
                        <img class="ui rounded small image" src="/media/{{ img_path }}">
                    </div>
                    <div class="ten wide column">
                        <div class="header">
                            <b>Similarity</b>
                        </div>
                        <p>{{ similarity }} %</p>
                        {% if duration %}
                        <div class="header">
                            <b>Execution time</b>
                        </div>
                        <p>{{ duration }}</p>
                        {% endif %}
                    </div>
                    <div class="three wide column">
                        <img class="ui rounded small image" src="{{ orig_path }}">
                    </div>
                </div>
            </div>
            {% endif %}
        </div>

        <div class="right aligned column" style="padding:0 0 50px 0;">
            <button class="positive ui button" onClick="window.location.href='/'">Go to the Main page</button>
        </div>

        <div class="ui divider"></div>
        <div class="right aligned column">
            <a href="https://github.com/waikiki-korea" target="_blank"><img
                    src="{% static 'img/GitHub-Mark-64px.png' %}" style="width:25px;"></a>
            <p>Copyright &copy; 2022 <b>Team Waikiki</b> all rights reserved.</p>
        </div>
    </div>
</div>
{% endblock %}

waikiki/templates/ono/test_image.html
{% extends 'ono/base.html' %}
{% load static %}
{% block content %}
<script>
    $(document).ready(function () {
        $.getScript("{% static 'js/ono-0.1.0.js' %}", function () {
        });
    });

    function submit_loading() {
        $("#submit_button").addClass('loading');
    }
</script>

<div class="ui stackable four column centered grid" style="margin:auto;">
    <div class="two column centered row">
        <div class="column" style="padding-top:25px;">
            <form class="ui form" action="{% url 'ono:test_image' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="field">
                    <label>Image</label>
                    <input type="file" name="test_image" id="test_image" accept="image/*" multiple>
                </div>

                <div align="right">
                    <button class="ui blue submit button" type="submit" id="submit_button"
                        onClick="submit_loading()">Submit</button>
                </div>
            </form>
        </div>

        <div class="ui divider"></div>

    </div>
    <div class="one column centered row">
        <div class="right aligned column">
            <a href="https://github.com/waikiki-korea" target="_blank"><img
                    src="{% static 'img/GitHub-Mark-64px.png' %}" style="width:25px;"></a>
            <p>Copyright &copy; 2022 <b>Team Waikiki</b> all rights reserved.</p>
        </div>
    </div>
</div>
{% endblock %}